<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

    <div class="control-group">
        <?php echo  $this->formLabel($form->get('firstname')); ?>
        <div class="controls">
            <?php echo  $this->formElement($form->get('firstname')); ?>
            <span class="help-block errors"><?php echo  $this->formElementErrors($form->get('firstname')); ?></span>
        </div>
    </div>

    <div class="control-group">
        <?php echo  $this->formLabel($form->get('lastname')); ?>
        <div class="controls">
            <?php echo  $this->formElement($form->get('lastname')); ?>
            <span class="help-block errors"><?php echo  $this->formElementErrors($form->get('lastname')); ?></span>
        </div>
    </div>

    <div class="control-group">
        <?php echo  $this->formLabel($form->get('email')); ?>
        <div class="controls">
            <?php echo  $this->formElement($form->get('email')); ?>
            <span class="help-block errors"><?php echo  $this->formElementErrors($form->get('email')); ?></span>
        </div>
    </div>

    <div class="control-group">
        <?php echo  $this->formLabel($form->get('password')); ?>
        <div class="controls">
            <?php echo  $this->formElement($form->get('password')); ?>
            <span class="help-block errors"><?php echo  $this->formElementErrors($form->get('password')); ?></span>
        </div>
    </div>

    <div class="form-actions">
        <?php echo  $this->formSubmit($form->get('submit')); ?>
    </div>
<?php echo  $this->form()->closeTag(); ?>