<?php
    $url_order = 'asc';
    if ($field == 'id')
        $url_order = $type == 'asc' ? 'desc' : 'asc';
    elseif ($field == 'firstname')
        $url_order = $field == 'asc' ? 'desc' : 'asc';
?>
<a href="<?php echo $this->url('users/add')?>" class='btn btn-primary'>
    <?php echo $this->translate('__add_user')?>
</a>

<br/>
<br/>

<table>
    <thead>
        <tr>
            <th>
                <a href="/users/order/id/<?php echo $url_order?>"><?php echo $this->translate('__user_id')?> <?php if ($field == 'id'): ?><i class="icon-chevron-<?php echo $url_order == 'asc' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                <?php // echo $this->translate('__user_id')?>
            </th>
            <th>
                <?php echo $this->translate('__user_firstname')?>
            </th>
            <th>
                <?php echo $this->translate('__user_lastname')?>
            </th>
            <th>
                <?php echo $this->translate('__user_address')?>
            </th>
            <th>
                <?php echo $this->translate('__user_birthdate')?>
            </th>
            <th>
                <a href="/users/order/email/<?php echo $url_order?>"><?php echo $this->translate('__user_email')?> <?php if ($field == 'email'): ?><i class="icon-chevron-<?php echo $url_order == 'asc' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                <?php echo $this->translate('__user_email')?>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php
    /* @var $user \Application\Entity\User */
    foreach($this->users as $user)
    {
        ?>
        <tr>
        <td>
            <?php echo $user['id']?>
        </td>
        <td>
            <?php echo $user['profile']['firstname']?>
        </td>
        <td>
            <?php echo $user['profile']['lastname']?>
        </td>
        <td>
            <?php echo $user['profile']['address']?>
        </td>
        <td>
            <?php echo $user['profile']['birthdate']?>
        </td>
        <td>
            <a href='mailto:<?php echo $user['email']?>'>
                <?php echo $user['email']?>
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url('users/edit', array('user_id'   =>  $user['id']))?>" class="btn btn-success">
                <?php echo $this->translate('__edit_user')?>
            </a>
           <a href="<?php echo $this->url('users/remove', array('user_id'   =>  $user['id']))?>" class="btn btn-danger">
            <?php echo $this->translate('__remove_user')?>
           </a>
        </td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>